
package Ventanas;

import javax.swing.WindowConstants;
import Clases.conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Administrador extends javax.swing.JFrame {
    String usuario,nombre_usuario;
    public static int sesion_usuario;
    public Administrador() {
        initComponents();
        usuario = Login.usuario ;
        sesion_usuario=1;
        setSize(650,430);
        setResizable(false);
        setTitle("Administrador - Sesion de " + usuario);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        try {
            Connection con = conexion.conectar();
            PreparedStatement val = con.prepareStatement("select nombre_usuario from usuarios where username ='"
                    + usuario + "'");
            ResultSet resulba = val.executeQuery();
            if (resulba.next()){
                nombre_usuario = resulba.getString("nombre_usuario");
                jLabeluser.setText(nombre_usuario);
                
            }
        } catch (SQLException e) {System.err.println("Error de conexion desde la ventana administrador");
        }
      
    }
@Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgestionar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btcapturista = new javax.swing.JButton();
        bttecnico = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btregistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabeluser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setSize(new java.awt.Dimension(650, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btgestionar.setBackground(new java.awt.Color(0, 0, 0));
        btgestionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/informationuser.png"))); // NOI18N
        btgestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgestionarActionPerformed(evt);
            }
        });
        getContentPane().add(btgestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 110, 100));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 110, 100));

        btcapturista.setBackground(new java.awt.Color(0, 0, 0));
        btcapturista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/capturista.png"))); // NOI18N
        btcapturista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcapturistaActionPerformed(evt);
            }
        });
        getContentPane().add(btcapturista, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, 100));

        bttecnico.setBackground(new java.awt.Color(0, 0, 0));
        bttecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tecnico.png"))); // NOI18N
        bttecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttecnicoActionPerformed(evt);
            }
        });
        getContentPane().add(bttecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 110, 100));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 110, 100));

        btregistrar.setBackground(new java.awt.Color(0, 0, 0));
        btregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addUser.png"))); // NOI18N
        btregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 110, 100));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gestionar usuarios");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 100, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Registrar usuario");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 120, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Panel capturista");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 100, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Panel tecnico");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 70, 20));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Acerca");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 70, 20));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Gestionar");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 70, 20));

        jLabeluser.setFont(new java.awt.Font("Cambria", 1, 22)); // NOI18N
        jLabeluser.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabeluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregistrarActionPerformed
      new Registrar_usuarios().setVisible(true);
      
    }//GEN-LAST:event_btregistrarActionPerformed

    private void btgestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgestionarActionPerformed
        new gestionar_usuarios().setVisible(true);
    }//GEN-LAST:event_btgestionarActionPerformed

    private void btcapturistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcapturistaActionPerformed
        new Capturista ().setVisible(true);
       
    }//GEN-LAST:event_btcapturistaActionPerformed

    private void bttecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttecnicoActionPerformed
        new Tecnico().setVisible(true);
    }//GEN-LAST:event_bttecnicoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new acercade().setVisible(true);
                
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcapturista;
    private javax.swing.JButton btgestionar;
    private javax.swing.JButton btregistrar;
    private javax.swing.JButton bttecnico;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabeluser;
    // End of variables declaration//GEN-END:variables
}
