
package Ventanas;
import Clases.conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
public class Registrar_usuarios extends javax.swing.JFrame {
    String user;
    public Registrar_usuarios() {
        initComponents();
        user= Login.usuario;
        setTitle ("Registro de usuario - "+user);
        setResizable (false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);  
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        boxpermisos = new javax.swing.JComboBox<>();
        btagregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Permisos de:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 90, 20));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 70, 20));

        txtemail.setBackground(new java.awt.Color(51, 51, 51));
        txtemail.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtemail.setForeground(new java.awt.Color(255, 255, 255));
        txtemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtemail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 210, 30));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 70, 20));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registro de usuarios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 270, 30));

        txttelefono.setBackground(new java.awt.Color(51, 51, 51));
        txttelefono.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txttelefono.setForeground(new java.awt.Color(255, 255, 255));
        txttelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 210, 30));

        txtnombre.setBackground(new java.awt.Color(51, 51, 51));
        txtnombre.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(255, 255, 255));
        txtnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 210, 30));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Télefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 70, 20));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 70, 20));

        txtusername.setBackground(new java.awt.Color(51, 51, 51));
        txtusername.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 210, 30));

        txtpassword.setBackground(new java.awt.Color(51, 51, 51));
        txtpassword.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 210, 30));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 70, 20));

        boxpermisos.setBackground(new java.awt.Color(51, 51, 51));
        boxpermisos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista", "Tecnico" }));
        getContentPane().add(boxpermisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 130, 30));

        btagregar.setBackground(new java.awt.Color(204, 204, 204));
        btagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        btagregar.setToolTipText("");
        btagregar.setBorderPainted(false);
        btagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btagregar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btagregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btagregarActionPerformed(evt);
            }
        });
        getContentPane().add(btagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 140, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btagregarActionPerformed
        int permisos,validacion = 0;
        String nombre, mail, telefono,username,pass,permisos_string="";
        nombre = txtnombre.getText().trim();
        mail = txtemail.getText().trim();
        telefono = txttelefono.getText().trim();
        username = txtusername.getText().trim();
        pass = txtpassword.getText().trim();
        permisos = boxpermisos.getSelectedIndex() + 1 ;
        if (mail.equals("")){
            txtemail.setBackground(Color.red);
            validacion ++;
        }
        if (telefono.equals("")){
            txttelefono.setBackground(Color.red);
            validacion ++;
        }
        if (username.equals("")){
            txtusername.setBackground(Color.red);
            validacion ++;
        }
        if (pass.equals("")){
            txtpassword.setBackground(Color.red);
            validacion ++;
        }
        if (nombre.equals("")){
            txtnombre.setBackground(Color.red);
            validacion ++;
        }
        if (permisos ==1) {
            permisos_string = "Administrador";
        } else if (permisos ==2) {
            permisos_string = "Capturista";
        } else if (permisos ==3) {
            permisos_string = "Tecnico";
        }   
        try {
            Connection con = conexion.conectar();
            PreparedStatement val = con.prepareStatement(
                    "select username from usuarios where username = '" + username +"'");
            ResultSet resulba = val.executeQuery();
            if (resulba.next()) {
                txtusername.setBackground(Color.red);
                JOptionPane.showMessageDialog(null,"Nombre de usuario en uso");
                con.close();
            } else {
                if (validacion == 0) {
                    try {
                        Connection con2 = conexion.conectar();
                        PreparedStatement val2 = con2.prepareStatement(
                                "insert into usuarios values (?,?,?,?,?,?,?,?,?)");
                        val2.setInt(1, 0);
                        val2.setString(2, nombre);
                        val2.setString(3, mail);
                        val2.setString(4, telefono);
                        val2.setString(5, username);
                        val2.setString(6, pass);
                        val2.setString(7, permisos_string);
                        val2.setString(8, "Activo");
                        val2.setString(9, user);
                        val2.executeUpdate();
                        con2.close();
                    
                    txtemail.setText("");
                    txtnombre.setText("");
                    txttelefono.setText("");
                    txtusername.setText("");
                    txtpassword.setText("");
                    boxpermisos.setSelectedIndex(0);
                    
                    txtemail.setBackground(Color.green); 
                    txtnombre.setBackground(Color.green);
                    txttelefono.setBackground(Color.green);
                    txtusername.setBackground(Color.green);
                    txtpassword.setBackground(Color.green);
                    JOptionPane.showMessageDialog(null,"Usuario registrado");
                    dispose();
                    } catch (SQLException e) {
                        System.err.println("Error de conexion desde la ventana registro");
                        JOptionPane.showMessageDialog(null,"¡Error al registrar usuario! Contactese con el administrador");
                    }
 
                   
                } else {
                    JOptionPane.showMessageDialog(null,"Debe de llenar todos los campos");
                }
                con.close();
            }
        } catch (SQLException e) {
            System.err.println("Error en validar nombre de usuario" + e);
            JOptionPane.showMessageDialog(null,"¡Error al validar el usuario! Contactese con el administrador");
        }
        
        
        
    }//GEN-LAST:event_btagregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxpermisos;
    private javax.swing.JButton btagregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
